# To trigger pipeline push a new tag

on:
  push:
    tags:
      - '*'

env:
  DOCKERHUB_USERNAME: ${{ vars.DOCKERHUB_USERNAME }}
  TAG: ${{ github.ref#refs/tags/ }}

jobs:
  docker_push:
    runs-on: ubuntu-22.04
    name: Deploy Image
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub as ${{ env.DOCKERHUB_USERNAME }}
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build Image ${{ env.DOCKERHUB_USERNAME }}/istio-operator:${{ env.TAG }}
        run: IMAGE=docker.io/${{ env.DOCKERHUB_USERNAME }}/istio-operator:${{ env.TAG }} make image
      - name: Push Image ${{ env.DOCKERHUB_USERNAME }}/istio-operator:${{ env.TAG }}
        run: docker push docker.io/${{ env.DOCKERHUB_USERNAME }}/istio-operator:${{ env.TAG }}
