# To trigger pipeline push a new tag

on:
  push:
    tags:
      - '*'
    branches:
      - maistra-2.5

jobs:
  docker_push:
    runs-on: ubuntu-22.04
    name: A job to say hello
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: IMAGE=docker.io/${{ secrets.DOCKERHUB_USERNAME }}/istio-operator:latest make image
      - run: docker push docker.io/${{ secrets.DOCKERHUB_USERNAME }}/istio-operator:${{ github.ref }}
