# To trigger pipeline push a new tag

on:
  push:
    tags:
      - '*'

env:
  DOCKERHUB_USERNAME: ${{ vars.DOCKERHUB_USERNAME }}

jobs:
  docker_push:
    runs-on: ubuntu-22.04
    name: Deploy Image
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub as $DOCKERHUB_USERNAME
        uses: docker/login-action@v3
        with:
          username: $DOCKERHUB_USERNAME
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build Image
        run: IMAGE=docker.io/$DOCKERHUB_USERNAME/istio-operator:latest make image
      - name: Push Image
        run: docker push docker.io/$DOCKERHUB_USERNAME/istio-operator:${{ github.ref }}
